# -*- coding: utf-8 -*-
"""Aiml internship remote devspher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hpmH6b0YsemOS6bIPDCWvIdDX1Dgu7SF
"""



"""**Week 1 Ai Ml**"""

#Ai code week 1
print("======================================")
print("   AI Career Recommendation System")
print("======================================")

interest = input(
    "\nWhat are you interested in? "
    "(programming/design/business/data): "
).lower()

experience = input(
    "Do you have programming experience? (yes/no): "
).lower()

if interest == "programming" and experience == "yes":
    recommendation = "Software Developer"

elif interest == "programming" and experience == "no":
    recommendation = "Start learning Python and become a Software Developer"

elif interest == "data":
    recommendation = "Data Analyst / Machine Learning Engineer"

elif interest == "design":
    recommendation = "UI/UX Designer"

elif interest == "business":
    recommendation = "Business Analyst"

else:
    recommendation = "Explore different fields to discover your interest."

print("\n======================================")
print("          AI RECOMMENDATION")
print("======================================")

print("Your Interest:", interest)
print("Programming Experience:", experience)
print("Recommended Career:", recommendation)

print("\nAI Decision completed successfully!")



#ml code
import pandas as pd

print("======================================")
print("       ML WEEK 1 - DATA ANALYSIS")
print("======================================")

df = pd.read_csv("students.csv")

print("\nDataset loaded successfully!")

print("\n========== FIRST 5 ROWS ==========")
print(df.head())

print("\n========== DATASET INFO ==========")
df.info()

print("\n========== SUMMARY STATISTICS ==========")
print(df.describe())

print("\n========== MISSING VALUES ==========")
print(df.isnull().sum())

numeric_columns = df.select_dtypes(include="number").columns

for column in numeric_columns:
    df[column] = df[column].fillna(df[column].mean())

    text_columns = df.select_dtypes(include="object").columns

    for column in text_columns:
        df[column] = df[column].fillna("Unknown")

        df = df.drop_duplicates()

        print("\n========== CLEANED DATASET ==========")
        print(df.head())

        print("\n========== MISSING VALUES AFTER CLEANING ==========")
        print(df.isnull().sum())

        df.to_csv("cleaned_students.csv", index=False)

        print("\nData cleaning completed successfully!")
        print("Cleaned dataset saved as cleaned_students.csv")